apiVersion: v1
kind: Pod
metadata:
  name: sharded-memcache-ambassador
  labels:
    name: sharded-memcache-ambassador
spec:
  containers:
  # This is where the application container would go, for example
  # - name: nginx
  #   image: nginx
  # This app container can access twemproxy router via localhost:11211

  # This is the ambassador container
  - name: twemproxy
    image: ganomede/twemproxy
    command:
    - nutcracker
    - -c
    - /etc/config/nutcracker.yaml
    - -v
    - "7"
    - -s
    - "6222"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
        - mountPath: /etc/config
          name: config-volume
  
  volumes:
    - name: config-volume
      configMap:
        name: twem-config
