apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dictionary-server
  template:
    metadata:
      labels:
        app: dictionary-server
    spec:
      containers:
      - name: server
        image: brendanburns/dictionary-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
