apiVersion: v1
kind: Pod
metadata:
  name: sharded-memcache-ambassador
  labels:
    name: sharded-memcache-ambassador
spec:
  containers:
  # This is where the application container goes
  - name: gomem
    image: github.com/weak-head/gomem:0.0.1
    env:
    - name: MEMCACHE_HOST
      value: "localhost"
    - name: MEMCACHE_PORT
      value: "11211"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

  # This is the ambassador container
  - name: twemproxy
    image: ganomede/twemproxy
    command:
    - nutcracker
    - -c
    - /etc/config/nutcracker.yaml
    - -v
    - "7"
    - -s
    - "6222"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
        - mountPath: /etc/config
          name: config-volume
  
  volumes:
    - name: config-volume
      configMap:
        name: twem-config
