apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: scraper
  namespace: default
  label:
    created-by: kubeless
    function: scraper
spec:
  runtime: python3.7
  timeout: "180"
  handler: scraper.main
  deps: ""
  function-content-type: url+zip
  function: https://github.com/weak-head/designing-distributed-systems/releases/download/v0.1-pre-alpha/scraper_package.zip