apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example

spec:
  containers:
  # This is where the application container would go, for example
  # - name: nginx
  #   image: nginx

  # This is the ambassador container
    - name: twemproxy
      image: ganomede/twemproxy
      command: 
      - nutcracker 
      - -c
      - /etc/config/twemproxy.config.yaml
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
          name: twem-config
