apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-twemproxy
  labels:
    name: shared-twemproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shared-twemproxy
  template:
    metadata:
      labels:
        app: shared-twemproxy
    spec:
      containers:
        - name: twemproxy
          image: ganomede/twemproxy
          command:
          - nutcracker
          - -c
          - /etc/config/nutcracker.yaml
          - -v
          - "7"
          - -s
          - "6222"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: twem-config
