# This is the 'experiment' service
apiVersion: v1
kind: Service
metadata:
  name: experiment
  labels:
    app: experiment
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: experiment
---
# This is the 'prod' service
apiVersion: v1
kind: Service
metadata:
  name: prod
  labels:
    app: prod
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: prod
